### ISSUE TITLE
Pywalfox doesn't update

### ISSUE THREAD

**Issue by YuvanMichael** [Frewacom/pywalfox#131]
Occasionally, I get reminders from pywalfox saying the native host messenger is outdated. Saying that I'm gonna miss out on new features. But on Arch Linux, yay says that everything is up to date. Including python-pywalfox. Everything works fine. But just the message concerns me. I don't want to install again through pip. Unless you think it would solve the issue.

**Comment by YuvanMichael** [comment]
Hello? I would like some clarification. Please tell me why this is happening?

**Comment by YuvanMichael** [comment]
Hello? Taking quite a while to respond?

**Comment by Frewacom** [comment]
Hi, 

Check if the version of python-pywalfox is at least 2.7.x. If it is, it is most likely just a bug, especially if it only occurs occasionally. I would recommend muting the update notifications and just make sure that your system is up-to-date, since that will automatically update pywalfox when needed.
