### ISSUE TITLE
Update seems to have broken the plugin

### ISSUE THREAD

**Issue by GideonWolfe** [Frewacom/pywalfox#31]
I updated `pywalfox` with 

`pip3 --user --upgrade pywalfox`

and ran `git pull origin master` in the directory I cloned pywalfox into.

When I open the plugin settings, it fails to fetch pywal colors, and the buttons for enabling the `css` files hang. 

Every time I open Firefox, `pywalfox` prompts me for an update, even though I have already ran the steps above.

The url bar and drop down menu are no longer themed for me, suggesting the `css` is no longer working

![pywalfox](https://user-images.githubusercontent.com/32942052/82745780-13dc6c00-9d3d-11ea-97be-5bf5586080ab.png)

**Comment by Frewacom** [comment]
Seems like you are still using the old daemon. You can remove the repository if you only used it for the daemon and use pip only from now on. 

Also, make sure that the installed version is `2.3`, by running `pywalfox -v`. If not, upgrade via pip. 

Rerun the setup (`pywalfox setup`) and make sure that the manifest installation path that is outputted  is in the `.mozilla/native-messaging-hosts` folder of your home directory, e.g. `/home/<username>/.mozilla/native-messaging-hosts/pywalfox.json`

**Comment by GideonWolfe** [comment]
Ok so I deleted the folder I had originally used to install `pywalfox`. I have already installed it with pip. `pywalfox -v` gives me 

```
v2.3
```

I reinstalled the browser extension, which seems to default to `v2.0.1` and then warns me about the version.

The output of `pywalfox setup` confirmed it's going to the right place

```
/home/gideon/.mozilla/native-messaging-hosts/pywalfox.json
```

**Comment by GideonWolfe** [comment]
When I try to run the daemon manually with `pywalfox -p --verbose daemon`
```
[05-24-2020 11:36:37] DEBUG:Using python 3.8.3
[05-24-2020 11:36:37] ERROR:Could not find default Firefox profile
[05-24-2020 11:36:37] DEBUG:Setup socket server using AF_UNIX (linux)
[05-24-2020 11:36:37] DEBUG:Successfully bound socket to: /tmp/pywalfox_socket
```

**Comment by Frewacom** [comment]
Do you get any errors? You can check the browser console `Tools > Web developer > Browser console` and also in `about:debugging` and click inspect on the Pywalfox addon. 

What does the `Debugging` section of the extension say?

As for the CSS, the daemon can't find you profile directory so you won't be able to enable it from the Settings page. That might be fixed in the [next update](https://github.com/Frewacom/pywalfox-native/blob/firefox-profile-path-fix/pywalfox/custom_css.py) of the daemon.

**Comment by GideonWolfe** [comment]
Thanks for the timely responses. I'm not quite sure what I'm doing wrong. My buddy had the *exact* same issue with the pywalfox update and solved it by 

1. Removing cloned `pywalfox` folder
2. Reinstalling `firefox`
3. updating `pywalfox` pip module

But this hasn't worked for me.

The only error messages I see are the ones depicted in the above image. For what it's worth when I switched to my laptop, the issue occurred there as well, yet I get no errors in the Debug window when I click buttons.

I've checked both the debugging areas you mentioned but nothing `pywalfox` related jumped out at me.

**Comment by Frewacom** [comment]
In the `Debugging` section, does it still say `Connected` and `version not set`?

**Comment by GideonWolfe** [comment]
Yep, exactly that.

**Comment by Frewacom** [comment]
I am kind of lost, to be honest.

If you run `pywalfox update` in your terminal, does that do something? Errors/debugging output, anything? 

The daemon should be setup correctly since you weren't getting any errors, and the `Connected` means that the daemon have been started by Firefox and is currently running. If there were any errors with the daemon itself, it would have crashed and Firefox would have killed the connection.

**Comment by GideonWolfe** [comment]
`pywalfox --verbose -p update`
```
ERROR:root:Could not find socket: /tmp/pywalfox_socket
```

**Comment by Frewacom** [comment]
I forgot I implemented logging, perhaps that will tell us something. What does `pywalfox log` say?

**Comment by GideonWolfe** [comment]
```
[05-24-2020 11:35:46] DEBUG:Using python 3.8.3
[05-24-2020 11:35:46] DEBUG:Using python 3.8.3
[05-24-2020 11:35:46] ERROR:Could not find default Firefox profile
[05-24-2020 11:35:46] DEBUG:Setup socket server using AF_UNIX (linux)
[05-24-2020 11:35:46] DEBUG:Successfully bound socket to: /tmp/pywalfox_socket
[05-24-2020 11:36:08] DEBUG:Cleanup
```

**Comment by Frewacom** [comment]
By default, only errors are logged when running via Firefox. So, since there are errors, I think we can assume that either there are no errors, or the code did not execute.

**Comment by GideonWolfe** [comment]
I'm not too sure what changed on my end, but the issue appeared on both my machine and my friends machine after the update yesterday.

Please let me know if there's anything else I can do to assist on my end

**Comment by Frewacom** [comment]
Some things that you can try:

What does your `~/.mozilla/native-messaging-hosts/pywalfox.json` look like?
What path is the executable installed at `whereis pywalfox`? Is that path in your `$PATH`?

Try modifying the `main.sh` script (you can find the path in the `pywalfox.json` file) and replace `pywalfox daemon` with `pywalfox daemon --verbose`, restart Firefox, click some buttons in the Settings page and check the logs `pywalfox log`. You should see new output with the current time. If not, then the issue must be with the daemon setup.

**Comment by Frewacom** [comment]
> Do you get any errors? You can check the browser console `Tools > Web developer > Browser console` and also in `about:debugging` and click inspect on the Pywalfox addon.
> 
> What does the `Debugging` section of the extension say?
> 
> As for the CSS, the daemon can't find you profile directory so you won't be able to enable it from the Settings page. That might be fixed in the [next update](https://github.com/Frewacom/pywalfox-native/blob/firefox-profile-path-fix/pywalfox/custom_css.py) of the daemon.

Could you also restart Firefox and post images of the output you got from there? There probably is nothing, but doesn't hurt to make sure.

**Comment by GideonWolfe** [comment]
Here is a screenshot

![ff](https://user-images.githubusercontent.com/32942052/82765258-f0abce00-9dc9-11ea-9643-9f15961f1723.png)

**Comment by GideonWolfe** [comment]
And the console

![debug](https://user-images.githubusercontent.com/32942052/82765284-3f596800-9dca-11ea-8f92-4866c13ebac8.png)

**Comment by Frewacom** [comment]
Nothing out of the ordinary it seems. Most of the errors are not even from Pywalfox.

**Comment by GideonWolfe** [comment]
I tried creating a new firefox profile. The issue persists of `pywalfox` not connecting, but the drop downs are themed, unlike on my usual profile...
![2020-05-24-192757_2560x1600_scrot](https://user-images.githubusercontent.com/32942052/82772730-e3580900-9df4-11ea-859e-681fa05b0ef3.png)

**Comment by GideonWolfe** [comment]
It just seems like something is "sticking around", causing the pip version of `pywalfox`. Because the pip module is up to date. I deleted the original `Pywalfox` folder, are there any other straggler files that could cause this behavior?

I scrubbed the entire `.mozilla` directory of `pywalfox` but nothing works

**Comment by fubarhouse** [comment]
I've done something similar as I have the same issue, perhaps this  could be useful:

![image](https://user-images.githubusercontent.com/3070264/82775019-c883a400-9e89-11ea-9713-4da2e3dd7b66.png)

**Comment by Paul-Houser** [comment]
I had this same issue and was able to fix it by doing these steps in this order:
1. Uninstall everything pywalfox related with
`pywalfox uninstall`
`pip3 uninstall pywalfox`
2. Deleted all straggler files on my system related to pywal fox
3. Uninstall firefox
4. installed pywalfox from pip globally, rather than the user install
5. install firefox and the pywalfox plugin

In terminal:
6. `pywalfox setup`
7. `pywalfox update`

Rebooted my computer after this and then went to the plugin settings page and was able to successfully fetch pywal colors.

It took me quite a while to get it to work after the update, and I tried lots of things before this, so maybe something I did earlier that isn't included here is also important to fixing it. The only notable thing I remember doing before this is deleting the directory `$HOME/.mozilla/native-messaging-hosts`, but I think that probably would've also been deleted when running `pywalfox uninstall`. Could be wrong though.

**Comment by Frewacom** [comment]
Running the setup of the previous version installed one single file; `~/.mozilla/native-messaging-hosts/pywalfox.json`. Nothing else. It should not really be necessary to remove the old repo, reinstall Firefox or even restarting your system. It _should_ be enough to run `pywalfox setup`, update the addon and restart Firefox. 

Simply running `pywalfox update` should replace the old `pywalfox.json` manifest and Firefox will automatically use the correct daemon, since it only runs what is defined in the manifest. The new and old setup are basically the same, except one was written in bash and the other in python. 

One thing that came to mind is browser state. It should be the only thing that persists between versions and setups, so perhaps you could try the following and see if that makes a difference:

1. Open the settings page of the addon
2. Right click > Inspect element > Console 
3. Run `browser.storage.local.clear()` (will remove all saved data in local storage for Pywalfox)
4. Restart Firefox

**Comment by srappan** [comment]
I manage to figure out a work around, seem there is some permission issues with the daemon
```
❯ pywalfox daemon
Traceback (most recent call last):
  File "/usr/bin/pywalfox", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/pywalfox/__main__.py", line 102, in main
    handle_args(args)
  File "/usr/lib/python3.8/site-packages/pywalfox/__main__.py", line 78, in handle_args
    setup_logging(args.verbose, args.print_mode)
  File "/usr/lib/python3.8/site-packages/pywalfox/utils/logger.py", line 43, in setup_logging
    create_rotating_log('', logging.ERROR) # use the root logger
  File "/usr/lib/python3.8/site-packages/pywalfox/utils/logger.py", line 16, in create_rotating_log
    handler = RotatingFileHandler(LOG_FILE_PATH, maxBytes=LOG_FILE_MAX_SIZE, backupCount=LOG_FILE_COUNT)
  File "/usr/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/pywalfox/daemon.log'
```
Just running this command seems to work. 
` sudo chown -R $USER /usr/lib/python3.8/site-packages/pywalfox/*  `

**Comment by Frewacom** [comment]
So the issue was fixed if you installed Pywalfox to `/usr/lib` rather than for your user only?

Either way, I should probably not save the log file somewhere else and that issue should be fixed.

**Comment by srappan** [comment]
I believe pip places files there regardless of user or system install.

**Comment by GideonWolfe** [comment]
Hmm i'm not getting permissions issues, I installed the `pywalfox` module with the `--user` flag. Clearing the browser storage had no effect.

**Comment by srappan** [comment]
So when you install a module with Pip, regardless of user or global, files are placed in the `/usr/lib/` area so if you don't have perms the daemon won't load and will crash.

**Comment by GideonWolfe** [comment]
When I run `pywalfox daemon`, it just hangs with no output. When I run 

`pywalfox -p --verbose daemon`, I get

```
[05-25-2020 12:05:50] DEBUG:Using python 3.8.3
[05-25-2020 12:05:50] DEBUG:Found chrome directory at path: /home/gideon/.mozilla/firefox/pw9fyemj.default-release/chrome
[05-25-2020 12:05:50] DEBUG:Setup socket server using AF_UNIX (linux)
[05-25-2020 12:05:50] DEBUG:Successfully bound socket to: /tmp/pywalfox_socket
```

**Comment by srappan** [comment]
Your daemon is workin fine.  Are you still not able to use the add on?

**Comment by GideonWolfe** [comment]
Nope, I still am unable to connect to the daemon in the plugin settings window, and I get a warning about pywalfox being outdated every time I restart Firefox.
________________________________

**Comment by fubarhouse** [comment]
I'm getting the same as @GideonWolfe... ☹️

**Comment by Paul-Houser** [comment]
Hello again everyone, I had the same issue on my laptop when I updated it just now, and since I was able to solve it on my desktop, I kept track of exactly how I solved it on my laptop. Here's what I came up with, that successfully fixed the issue on my laptop:

uninstall the pywalfox extension in Firefox
uninstall Firefox
uninstall the pip module for pywalfox
`sudo tree -f / | grep pywalfox` and delete anything that shows up
reboot (probably not necessary)
install Firefox
install pywalfox extension in Firefox

WITH FIREFOX OPEN:
`pip install --upgrade pywalfox`
and
`sudo pip install --upgrade pywalfox` 
(did both with and without sudo cause i was curious, both of them installed with out saying it was already installed... I don't know much about pip but maybe this is important)
`pywalfox setup`
close Firefox
open Firefox, click fetch colors on pywalfox settings page

**Comment by GideonWolfe** [comment]
@Paul-Houser can confirm that this fixed the issue on both my systems, and the second one worked without a reboot!

**Comment by fubarhouse** [comment]
It seems installing it via `sudo` and restarting has kicked it back into gear!

**Comment by Frewacom** [comment]
Any ideas as to why installing via `sudo` fixes the issue?

**Comment by fubarhouse** [comment]
Unfortunately not @Frewacom...

Despite not liking the need to do it, I would appreciate the findings of this issue make it into the readme or a wiki.

**Comment by thrifty-txt** [comment]
I experienced similar issues after pip installing with --user, with my Firefox plugin showing Connected and version not set. Fixed by adding the install folder of the pywalfox executable to my path variable, and restarting my X session to update the env for Firefox. No global install required.

**Comment by thrifty-txt** [comment]
If anyone reading this needs help changing their path variable, arch wiki has a good write-up: https://wiki.archlinux.org/index.php/Environment_variables#Defining_variables

**Comment by Jacob-Stokes** [comment]
> I experienced similar issues after pip installing with --user, with my Firefox plugin showing Connected and version not set. Fixed by adding the install folder of the pywalfox executable to my path variable, and restarting my X session to update the env for Firefox. No global install required.

This worked for me to resolve the issue, no need to install with `sudo`.

**Comment by Frewacom** [comment]
I have pushed an update to the native messaging application (version 2.6) that I hope should fix this issue. It no longer requires you to have `pywalfox` in your `PATH`. Instead, it relies on having one of `python`/`python3`/`python2.7` in your `PATH`, which a majority of you should have by default.

**Comment by Frewacom** [comment]
Closing for now.
