### ISSUE TITLE
Alter pallete with command?

### ISSUE THREAD

**Issue by GideonWolfe** [Frewacom/pywalfox#43]
I am the author of [Chameleon](https://github.com/GideonWolfe/Chameleon), a tool for theming your system with one command. We have spoken before :)

I successfully have automated `pywalfox` with a simple `pywalfox update` hook.

However, there are some settings that I **always** apply, which get reset every time new colors are fetched. This forces me to manually change it, breaking the seamless automation.

So my question is, are there any exposed commands that could accomplish this? The specific setting I am referring to is changing `Background Extra` to be the same color as `Background`, as I just think that looks better.

Thanks!!

**Comment by Frewacom** [comment]
There are currently no commands available that allows you to change this from the terminal.

However, you can modify the Palette template in the Settings page. It allows you to specify which pywal color (index 0-15) should be used when setting a certain color, e.g `Background extra`. If you want it to be the same as the `Background` color you just have to set them to the same index. All changes you make in the templates are persistent between fetches (though there are separate templates for light and dark mode). 

There is also a Theme template which allows you to change which color should be used for a certain element of the browser, so that is also an option if you still want to keep `Background extra` on certain elements. 

If you would prefer using a command to modify this, I’ll consider adding that in the future.

**Comment by GideonWolfe** [comment]
Ah, the template settings are just what I was looking for, as long as it stays persistent across refreshes :)

Would you be able to help me isolate this one element? I checked the visual guide you linked but nothing points directly to it, and I was messing with many of the template variables with no impact. 

![image](https://user-images.githubusercontent.com/32942052/91481381-2d6be300-e859-11ea-8cb9-786daece5c9f.png)

It seems to be a `toolbar*` variable, but I can't pin down which one. All I know is it gets fixed when I just change `background extra` -> `background` across the board.

**Comment by Frewacom** [comment]
I am not quite sure. For me, just updating the `Toolbar field` property updates the background of the entire url bar. I tried with and without the included CSS with the same result.

**Comment by GideonWolfe** [comment]
Ah, it would seem I didn't notice the `Save Template` button right in front of my face. I was confused because other changes (like altering colors in the main pallet) take effect immediately.  But it makes sense to have to "Save" a template.

Thanks!

**Comment by Frewacom** [comment]
You're welcome :)

The "Save" button could probably be removed. As you say, it would be more intuitive to update the theme directly, since that is the behaviour for most other settings. 

I'll close this for now and consider fixing that in a future update.
