### ISSUE TITLE
Could not find the folder to put custom CSS in?

### ISSUE THREAD

**Issue by prankousky** [Frewacom/Pywalfox#7]
Hi everybody,

I discovered `Pywalfox` by accident and really like the concept! Unfortunately, it does not work for me. I did

* `cd ~/code/git`
* `git clone git@github.com:Frewacom/Pywalfox.git`
* `cd Pywalfox/native-app`
* `bash setup.sh`

Got this

```
Creating 'native-messaging-hosts' folder in ~/.mozilla
Copying native messaging manifest to /home/my_user/.mozilla/native-messaging-hosts/pywalfox.json
Setting path to pywal-fetcher.py in the manifest
Setting execution permissions on pywal-fetcher.py
Finished.
```

Made sure that it points to the correct path:

* `cat ~/.mozilla/native-messaging-hosts/pywalfox.json`

```
{
  "name": "pywalfox",
  "description": "Automatically theme firefox using system colors generated by Pywal",
  "path": "/home/my_user/code/git/Pywalfox/native-app/pywal-fetcher.py",
  "type": "stdio",
  "allowed_extensions": [ "pywalfox@frewacom.org" ]
}

```

The Firefox extension is installed as well. When I click `Fetch pywal colors`, nothing happens; when I click `Disable theme`, I always get `Reset to default theme`.

Lastly, when I manually run `pywal-fetcher.py`, I get 

```
Traceback (most recent call last):
  File "./pywal-fetcher.py", line 135, in <module>
    sendMessage(createMessage('enableCustomCss', (False, 'Could not find the folder to put custom CSS in')))
NameError: name 'sendMessage' is not defined

```

I am currently using a `~/.mozilla/firefox/<profile>/chrome/usercontent.css` file already, if this is relevant... 

What can I do to still get the desired pywal colors in Firefox? Thank you for your help :)

**Comment by Frewacom** [comment]
I'm glad you like the concept. 

Your issue is completely my fault and should be fixed now. Run a git pull and try to run it manually again. If you don't get any errors, everything should work as expected and you should be able to fetch your colors using the addon (requires a restart of Firefox). I am not really sure why it says that it can not find the path, though.  

Also, you are free to use any custom CSS you want, but you also have to option of using the ones supplied by Pywalfox. If you want to use your own, you don't have to do anything.

**Comment by prankousky** [comment]
Thank you. Works perfectly now :)
