### ISSUE TITLE
I'm seeing outbound connections to a Cloudflare address. Why?

### ISSUE THREAD

**Issue by anthonyg-1** [Frewacom/pywalfox#70]
I saw some odd outbound connections via netstat and with lsof I saw that your plugin was making connections to the following IP: 104.16.248.249

Reference:
https://www.abuseipdb.com/check/104.16.248.249

Why?

**Comment by anthonyg-1** [comment]
Actually this may be the result of the "HTTPS Everywhere" Firefox plugin but lsof is showing a python process that's calling out to that address. When I disable your plugin, it stops. Is your plugin employing any telemetry? If not then you can close this issue and apologies for the confusion.

**Comment by Frewacom** [comment]
There is no telemetry in pywalfox, not in the addon, nor the native host. I am not making any external requests what-so-ever. 

It is really strange you are seeing these types of connections. I will have a look at my machine to see if I can see the same traffic.

**Comment by Frewacom** [comment]
> Actually this may be the result of the "HTTPS Everywhere" Firefox plugin but lsof is showing a python process that's calling out to that address. When I disable your plugin, it stops. Is your plugin employing any telemetry? If not then you can close this issue and apologies for the confusion.

The IP address is to [Mozilla's DNS-over-HTTPS server](https://bugzilla.mozilla.org/show_bug.cgi?id=1593176), which is probably why it happens when you have the "HTTPS Everywhere" plugin enabled. 

> There is no telemetry in pywalfox, not in the addon, nor the native host. I am not making any external requests what-so-ever.

On second thought, there is actually telemetry, but it is done entirely by Firefox, not pywalfox (with no option to disable as far as I am aware). It collects downloads, daily users, etc. If I were to guess, I would say that the traffic is related to this. Either way, it is not something I can control, but rather something that needs to be disabled locally for each user. 

As far as I can tell, the outbound traffic you are seeing is not related to pywalfox and should be completely harmless 🐼
