### ISSUE TITLE
Publish in AUR

### ISSUE THREAD

**Issue by morpheusthewhite** [Frewacom/pywalfox#9]
It would be good to have this very useful script on the Arch User Repository

**Comment by Frewacom** [comment]
Yes, this is something I am planning on doing eventually. I just want to get more a bit more feedback from users and make sure that there are no bugs/issues.

**Comment by Frewacom** [comment]
A quick update; I have created a new [repository](https://github.com/Frewacom/pywalfox-native) and rewritten the daemon with mostly the same features, but also support for Windows and Mac OS. The plan right now is to make it available to download using pip. 

It will be uploaded and available to use whenever I finish [v2.0.0](https://github.com/Frewacom/Pywalfox/tree/v2.0.0) of the extension, since the current version is not compatible with the new daemon.

**Comment by zkwinkle** [comment]
It would seem the python-pywalfox AUR package has been removed from the AUR, any reason for this?

**Comment by Frewacom** [comment]
The AUR package was not maintained by me, and I am not sure why it has been removed. I can look into publishing it myself ASAP.

**Comment by Frewacom** [comment]
> It would seem the python-pywalfox AUR package has been removed from the AUR, any reason for this?

I have reuploaded it to AUR and will be maintaining the package myself in the future. Hopefully everything should work as expected. Sorry for the inconvenience!
